//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class demoEntities1 : DbContext
    {
        public static demoEntities1 instance { get; set; }
        public static demoEntities1 GetContext() {
            {
                if (instance == null) ;
                instance = new demoEntities1();
            }
            return instance;
        }
        
        
        public demoEntities1()
            : base("name=demoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<taked_request> taked_request { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<userType> userType { get; set; }
    }
}
